version: '3'

services:
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - /home/xavier/dev/data/euro2021/pg_data:/var/lib/postgresql/data
      - /home/xavier/dev/data/euro2021/pg_backups:/pg_backups
        # - /Users/xjaner/dev/data/euro2021/pg_data:/var/lib/postgresql/data
        # - /Users/xjaner/dev/data/euro2021/pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - /static:/static
      - /home/xavier/dev/euro2020/euro2021:/opt/euro2021
        # - /Users/xjaner/dev/euro2021/euro2021:/opt/euro2021
    ports:
      - "8000:8000"
      - "8001:8001"
      - "587:587"
    depends_on:
      - db
        # command: uwsgi --ini /opt/euro2021/uwsgi.ini
    command: python /opt/euro2021/manage.py runserver 0.0.0.0:8000
    environment:
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
      - "EURO_GMAIL_APP_PWD=${EURO_GMAIL_APP_PWD}"

volumes:
  pg_data: {}
  pg_backups: {}
